/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package matador;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;
import java.util.Date;

/**
 *
 * @author and3k5
 */
public class MapBoard extends javax.swing.JPanel {

    /**
     * Creates new form MapBoard
     */
    public MapBoard() {
        initComponents();
    }

    private void rotateBy(int degrees,Graphics2D g2d) {
        /*g2d.translate(-(this.getWidth()/2), -(this.getHeight()/2));
        g2d.rotate(degrees*Math.PI/180);
        g2d.translate((this.getWidth()/2), (this.getHeight()/2));
        */
        AffineTransform transform=new AffineTransform();
        transform.rotate(Math.toRadians(degrees), 0 + this.getWidth()/2, 0 + this.getHeight()/2);
        g2d.transform(transform);
    }
    
    private void drawCircle(Graphics graphics) {
        Graphics2D g2d = (Graphics2D)graphics;
        setForeground(new Color(0,0,0));
        float circleLineWidth = 4;
        g2d.setStroke(new BasicStroke(circleLineWidth));
        int circle0_x=(int)(circleLineWidth/2);
        int circle0_y=(int)(circleLineWidth/2);
        int circle0_w=(int)(this.getWidth()-circleLineWidth);
        int circle0_h=(int)(this.getHeight()-circleLineWidth);
        int circle1_x=(int)((circleLineWidth/2)+((this.getWidth()-circleLineWidth)/4));
        int circle1_y=(int)((circleLineWidth/2)+((this.getHeight()-circleLineWidth)/4));
        int circle1_w=(int)((this.getWidth()-circleLineWidth)-((this.getWidth()-circleLineWidth)/2));
        int circle1_h=(int)((this.getHeight()-circleLineWidth)-((this.getHeight()-circleLineWidth)/2));
        
        g2d.drawArc(circle0_x, circle0_y, circle0_w, circle0_h, 0, 360);
        g2d.drawArc(circle1_x, circle1_y, circle1_w, circle1_h, 0, 360);
        int degWidth = 360/Game.fields.size();
        int w=this.getWidth();
        int h=this.getHeight();
        
        int iW=circle1_w-circle1_x;
        int iH=circle1_h-circle1_y;
        int oW=circle1_w-circle0_w;
        int oH=circle1_h-circle0_h;
        int field=0;
        for (int i=0;i<360;i+=degWidth) {
            int i2=i+90;
            int x1=(int) (w/2+Math.sin(i2*Math.PI/180)*iW);
            int y1=(int) (h/2+Math.cos(i2*Math.PI/180)*iH);
            int x2=(int) (w/2+Math.sin(i2*Math.PI/180)*-oW);
            int y2=(int) (h/2+Math.cos(i2*Math.PI/180)*-oH);
            g2d.drawLine(x1,y1,x2,y2);
            rotateBy(i2,g2d);
            
            if (Game.fields.get(field).getClass()==Street.class) {
                g2d.drawString(((Street)Game.fields.get(field)).Name, this.getWidth(), this.getHeight());
            }
            field++;
            // drawString inside rotateby
            rotateBy(-i2,g2d);
        }
    }
    
    @Override
    protected void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        drawCircle(graphics);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
