/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package matador;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author and3k5
 */
public class MortgageDialog extends javax.swing.JDialog {

    /**
     * Creates new form MortgageDialog
     */
    public int player=-1;
    public ArrayList<Integer> fieldsR;
    public DefaultListModel model;
    public MortgageDialog(java.awt.Frame parent, boolean modal,int pl) {
        super(parent, modal);
        initComponents();
        player=pl;
        model = new DefaultListModel();
        jList1.setModel(model);
        fieldsR = new ArrayList<>();
        for (Field field : Game.fields) {
            String name="";
            String type="";
            String mortgage="";
            Boolean mort=false;
            Boolean insert=false;
            if (field.getClass()==Brewery.class) {
                Brewery brew = ((Brewery)field);
                type="Bryggeri";
                name = brew.Name;
                mort = brew.Mortgage;
                if (brew.Owner==pl) {
                    System.out.print(type);
                    insert=true;
                }
            }else if (field.getClass()==Street.class) {
                Street street = ((Street)field);
                name = street.Name;
                type="Gade";
                mort = street.Mortgage;
                if (street.Owner==pl) {
                    System.out.print(type);
                    insert=true;
                }
            }else if (field.getClass()==ShippingLines.class) {
                ShippingLines sl = ((ShippingLines)field);
                name = sl.Name;
                type="Redderi";
                mort = sl.Mortgage;
                if (sl.Owner==pl) {
                    System.out.print(type);
                    insert=true;
                }
            }
            if (insert) {
                if (mort) {
                    mortgage="Pantsat";
                }else{
                    mortgage="Ikke pantsat";
                }
                System.out.println("Pantsæt: "+type+": "+name+" - "+mortgage);
                model.addElement(type+": "+name+" - "+mortgage);
                fieldsR.add(Game.fields.indexOf(field));
            }
        }
        
        
        jList1.updateUI();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Pantsæt / Afpantsætte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jList1.updateUI();
        
        if (jList1.getSelectedIndex()>=0) {
            Field f = Game.fields.get(fieldsR.get(jList1.getSelectedIndex()));
            if (f.getClass()==Brewery.class) {
                Brewery brew = ((Brewery)f);
                if (brew.Mortgage) {
                    brew.Mortgage=false;
                    Game.players.get(brew.Owner).ChangeMoney(-(brew.Price/2));
                }else{
                    brew.Mortgage=true;
                    Game.players.get(brew.Owner).ChangeMoney((brew.Price/2));
                }
            }else if (f.getClass()==Street.class) {
                Street street = ((Street)f);
                if (street.Mortgage) {
                    street.Mortgage=false;
                    Game.players.get(street.Owner).ChangeMoney(-(street.Price/2));
                }else{
                    if (street.Houses==0) {
                        street.Mortgage=true;
                        Game.players.get(street.Owner).ChangeMoney((street.Price/2));
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Du kan ikke pantsætte en gade med huse");
                    }
                }
            }else if (f.getClass()==ShippingLines.class) {
                ShippingLines sl = ((ShippingLines)f);
                if (sl.Mortgage) {
                    sl.Mortgage=false;
                    Game.players.get(sl.Owner).ChangeMoney(-(sl.Price/2));
                }else{
                    sl.Mortgage=true;
                    Game.players.get(sl.Owner).ChangeMoney((sl.Price/2));
                }
            }
            Game.gameboard.refreshGameControl();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MortgageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MortgageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MortgageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MortgageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MortgageDialog dialog = new MortgageDialog(new javax.swing.JFrame(), true,-1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
